# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v3.0.0
      with:
        version: ^7.1.0
        
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
      
    - run: pnpm i --no-frozen-lockfile
    - run: pnpm build:docs
    - run: |
        git config user.name loong.woo
        git config user.email longwunet@outlook.com
        git add .
        git commit -m "deploy"
        git push --force-with-lease
